import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { LogOut, Download, Clock, Trophy, Calendar, UserCheck } from 'lucide-react';

export const AdminDashboard: React.FC = () => {
  const { admin, quizResults, loginAsAdmin, logout } = useAuth();

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loginError, setLoginError] = useState('');

  const handleLogin = () => {
    const success = loginAsAdmin(username, password);
    if (!success) {
      setLoginError('Invalid username or password');
    } else {
      setLoginError('');
    }
  };

  const downloadPDF = (resultIndex: number) => {
    const result = quizResults[resultIndex];

    const pdfContent = `
QUIZ ASSESSMENT REPORT
${'='.repeat(60)}

Patient Information:
  Name: ${result.patientName}
  Age: ${result.patientAge}
  Date: ${new Date(result.timestamp).toLocaleString()}

Quiz Details:
  Genre: ${result.genre}
  Score: ${result.score} / ${result.totalQuestions}
  Time Taken: ${result.timeTaken} seconds

Question Results:
${result.correctAnswers
      .map((correct, idx) => `  Question ${idx + 1}: ${correct ? '✓ Correct' : '✗ Incorrect'}`)
      .join('\n')}

Assessment:
  ${result.prediction}

${'='.repeat(60)}
Generated by Assessment Quiz System
Admin: ${admin?.username}
    `.trim();

    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${result.patientName}_${result.genre}_Report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // ✅ Admin Login Page
  if (!admin) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-green-50 via-teal-50 to-blue-50 p-6">
        <div className="w-full max-w-md bg-white bg-opacity-90 rounded-3xl shadow-2xl p-10 text-center backdrop-blur-md">
          <div className="flex justify-center mb-6">
            <UserCheck className="text-blue-500" size={48} />
          </div>
          <h2 className="text-3xl font-bold text-gray-800 mb-4">Admin Login</h2>
          <p className="text-gray-600 mb-6">Enter your credentials to access the dashboard</p>

          <div className="space-y-4 text-left">
            <input
              type="text"
              placeholder="Username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full border border-gray-300 rounded-xl p-3 focus:outline-none focus:ring-2 focus:ring-blue-400"
            />
            <input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full border border-gray-300 rounded-xl p-3 focus:outline-none focus:ring-2 focus:ring-blue-400"
            />

            {loginError && (
              <p className="text-red-500 text-sm font-semibold text-center">{loginError}</p>
            )}

            <button
              onClick={handleLogin}
              className="w-full bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white font-bold py-3 rounded-xl shadow-lg transition-all duration-300"
            >
              Login
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ✅ Admin Dashboard (after login)
  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 via-teal-50 to-blue-50 p-6">
      <div className="max-w-7xl mx-auto">
        <div className="bg-white rounded-3xl shadow-2xl p-8 mb-6">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-4xl font-bold text-gray-800 mb-2">Admin Dashboard</h1>
              <p className="text-gray-600">Welcome, {admin?.username}</p>
            </div>
            <button
              onClick={logout}
              className="flex items-center gap-2 bg-red-500 hover:bg-red-600 text-white font-semibold py-3 px-6 rounded-xl transition-all duration-300"
            >
              <LogOut size={20} />
              Logout
            </button>
          </div>
        </div>

        <div className="bg-white rounded-3xl shadow-2xl p-8">
          <h2 className="text-3xl font-bold text-gray-800 mb-6">
            Quiz Results ({quizResults.length})
          </h2>

          {quizResults.length === 0 ? (
            <div className="text-center py-12">
              <p className="text-gray-500 text-xl">No quiz results available yet.</p>
            </div>
          ) : (
            <div className="space-y-6">
              {quizResults.map((result, index) => (
                <div
                  key={index}
                  className="border-4 border-gray-200 rounded-2xl p-6 hover:border-blue-300 transition-all duration-300"
                >
                  <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
                    <div className="flex-1">
                      <h3 className="text-2xl font-bold text-gray-800 mb-3">
                        {result.patientName} ({result.patientAge} years old)
                      </h3>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                        <div className="flex items-center gap-2 text-gray-700">
                          <Trophy className="text-yellow-500" size={20} />
                          <span className="font-semibold">Genre:</span>
                          <span>{result.genre}</span>
                        </div>

                        <div className="flex items-center gap-2 text-gray-700">
                          <Trophy className="text-blue-500" size={20} />
                          <span className="font-semibold">Score:</span>
                          <span>
                            {result.score} / {result.totalQuestions}
                          </span>
                        </div>

                        <div className="flex items-center gap-2 text-gray-700">
                          <Clock className="text-green-500" size={20} />
                          <span className="font-semibold">Time:</span>
                          <span>{result.timeTaken} seconds</span>
                        </div>

                        <div className="flex items-center gap-2 text-gray-700">
                          <Calendar className="text-purple-500" size={20} />
                          <span className="font-semibold">Date:</span>
                          <span>{new Date(result.timestamp).toLocaleDateString()}</span>
                        </div>
                      </div>

                      <div className="bg-yellow-50 border-2 border-yellow-200 rounded-xl p-4 mb-4">
                        <p className="font-semibold text-gray-800 mb-2">Assessment:</p>
                        <p className="text-lg text-gray-700">{result.prediction}</p>
                      </div>

                      <div className="bg-gray-50 rounded-xl p-4">
                        <p className="font-semibold text-gray-800 mb-2">Question Results:</p>
                        <div className="flex flex-wrap gap-2">
                          {result.correctAnswers.map((correct, idx) => (
                            <span
                              key={idx}
                              className={`px-3 py-1 rounded-lg font-semibold ${
                                correct
                                  ? 'bg-green-100 text-green-700'
                                  : 'bg-red-100 text-red-700'
                              }`}
                            >
                              Q{idx + 1}: {correct ? '✓' : '✗'}
                            </span>
                          ))}
                        </div>
                      </div>
                    </div>

                    <div>
                      <button
                        onClick={() => downloadPDF(index)}
                        className="flex items-center gap-2 bg-blue-500 hover:bg-blue-600 text-white font-bold py-4 px-6 rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 whitespace-nowrap"
                      >
                        <Download size={20} />
                        Download Report
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
